USE DATABASE QAD_PROD_STG;
USE SCHEMA QAD_STG;

CREATE OR REPLACE FILE FORMAT mycsvformat
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
TRIM_SPACE=TRUE,
FIELD_OPTIONALLY_ENCLOSED_BY='"',
DATE_FORMAT=AUTO,
TIME_FORMAT=AUTO,
TIMESTAMP_FORMAT=AUTO
ESCAPE_UNENCLOSED_FIELD=NONE;


CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__PT_MSTR
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/PT_MSTR_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__PT_MSTR;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__PT_MSTR
FROM @QAD_PROD_STG__QAD_STG__PT_MSTR
  FILE_FORMAT = (FORMAT_NAME = mycsvformat);

-- XXPT_MSTR   
CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__XXPT_MSTR
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/XXPT_MSTR_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__XXPT_MSTR;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__XXPT_MSTR
FROM @QAD_PROD_STG__QAD_STG__XXPT_MSTR
  FILE_FORMAT = (FORMAT_NAME = mycsvformat);
  
-- PS_MSTR 
CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__PS_MSTR
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/PS_MSTR_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__PS_MSTR;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__PS_MSTR
FROM @QAD_PROD_STG__QAD_STG__PS_MSTR
  FILE_FORMAT = (FORMAT_NAME = mycsvformat);
  
 -- SPT_DET
 
CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__SPT_DET
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/SPT_DET_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__SPT_DET;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__SPT_DET
FROM @QAD_PROD_STG__QAD_STG__SPT_DET
  FILE_FORMAT = (FORMAT_NAME = mycsvformat);
  
-- SO_MSTR

CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__SO_MSTR
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/SO_MSTR_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__SO_MSTR;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__SO_MSTR
FROM @QAD_PROD_STG__QAD_STG__SO_MSTR
  FILE_FORMAT = (FORMAT_NAME = mycsvformat);
  
  
 --SOD_DET
 
 CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__SOD_DET
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/SOD_DET_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__SOD_DET;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__SOD_DET
FROM @QAD_PROD_STG__QAD_STG__SOD_DET
  FILE_FORMAT = (FORMAT_NAME = mycsvformat);
  
  -- PO_MSTR
  
   CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__PO_MSTR
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/PO_MSTR_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__PO_MSTR;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__PO_MSTR
FROM @QAD_PROD_STG__QAD_STG__PO_MSTR
  FILE_FORMAT = (FORMAT_NAME = mycsvformat);
  
  --POD_DET 
    
   CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__POD_DET
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/POD_DET_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__POD_DET;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__POD_DET
FROM @QAD_PROD_STG__QAD_STG__POD_DET
  FILE_FORMAT = (FORMAT_NAME = mycsvformat);
  
   --CM_MSTR
   
CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__CM_MSTR
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/CM_MSTR_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__CM_MSTR;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__CM_MSTR
FROM @QAD_PROD_STG__QAD_STG__CM_MSTR
FILE_FORMAT = (FORMAT_NAME = mycsvformat); 

--IDH_HIST

CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__IDH_HIST
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/IDH_HIST_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__IDH_HIST;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__IDH_HIST
FROM @QAD_PROD_STG__QAD_STG__IDH_HIST
FILE_FORMAT = (FORMAT_NAME = mycsvformat); 

--IH_HIST

CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__IH_HIST
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/IH_HIST_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__IH_HIST;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__IH_HIST
FROM @QAD_PROD_STG__QAD_STG__IH_HIST
FILE_FORMAT = (FORMAT_NAME = mycsvformat); 

--PRH_HIST
   
  
CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__PRH_HIST
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/PRH_HIST_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__PRH_HIST;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__PRH_HIST
FROM @QAD_PROD_STG__QAD_STG__PRH_HIST
FILE_FORMAT = (FORMAT_NAME = mycsvformat); 

--WO_MSTR

CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__WO_MSTR
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/WO_MSTR_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__WO_MSTR;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__WO_MSTR
FROM @QAD_PROD_STG__QAD_STG__WO_MSTR
FILE_FORMAT = (FORMAT_NAME = mycsvformat); 

--WOD_DET 

CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__WOD_DET
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/WOD_DET_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__WOD_DET;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__WOD_DET
FROM @QAD_PROD_STG__QAD_STG__WOD_DET
FILE_FORMAT = (FORMAT_NAME = mycsvformat); 

--PI_MSTR

CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__PI_MSTR
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwstage/PI_MSTR_202311091230.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_STAGE__PI_MSTR;

COPY INTO QAD_PROD_STG.QAD_STG.DW_STAGE__PI_MSTR
FROM @QAD_PROD_STG__QAD_STG__PI_MSTR
FILE_FORMAT = (FORMAT_NAME = mycsvformat); 

--DW_CUSTOM.BOM_EXPLODE

CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__BOM_EXPLODE
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwcustom/BOM_EXPLODE_202311150107.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_CUSTOM__BOM_EXPLODE;

COPY INTO QAD_PROD_STG.QAD_STG.DW_CUSTOM__BOM_EXPLODE
FROM @QAD_PROD_STG__QAD_STG__BOM_EXPLODE
FILE_FORMAT = (FORMAT_NAME = mycsvformat); 

--DW_COMMON.COST_TOTAL_DIMENSION

CREATE OR REPLACE STAGE QAD_PROD_STG__QAD_STG__COST_TOTAL_DIMENSION
STORAGE_INTEGRATION = S3_WHOLESALE_DEV
URL = 's3://966612968161-us-east-1-dwp-dw-wholesale-stg-dev/dwprod01/dwcommon/COST_TOTAL_DIMENSION_202311150102.csv';

TRUNCATE TABLE IF EXISTS QAD_PROD_STG.QAD_STG.DW_COMMON__COST_TOTAL_DIMENSION;

COPY INTO QAD_PROD_STG.QAD_STG.DW_COMMON__COST_TOTAL_DIMENSION
FROM @QAD_PROD_STG__QAD_STG__COST_TOTAL_DIMENSION
FILE_FORMAT = (FORMAT_NAME = mycsvformat); 