name: Upload DBT

on:
  workflow_dispatch:
    branches: [main, dev, stage, prod]
  push:
    branches: [main, dev, stage, prod]
    paths:
      - dbt/**
      - dags/**
      - glue/jobs/**
  pull_request:
    paths:
      - dbt/**
      - dags/**
      - glue/jobs/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Set environment variables
        run: |
          echo "AWS_S3_BUCKET_NAME=AWS_S3_BUCKET_${GITHUB_REF_SLUG}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID_NAME=AWS_ACCESS_KEY_ID_${GITHUB_REF_SLUG}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY_NAME=AWS_SECRET_ACCESS_KEY_${GITHUB_REF_SLUG}" >> $GITHUB_ENV        
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Upload DBT files to S3
        uses: jakejarvis/s3-sync-action@master
        # with:
        #   args: --acl private --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{ secrets[env.AWS_S3_BUCKET_NAME] }}
          AWS_ACCESS_KEY_ID: ${{ secrets[env.AWS_ACCESS_KEY_ID_NAME] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[env.AWS_SECRET_ACCESS_KEY_NAME] }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: './dbt'
          DEST_DIR: 'dags/${{ env.REPO_NAME }}/dbt/'

      - name: Check if DAGs folder exists
        id: check_dags
        uses: andstor/file-existence-action@v2
        with:
          files: './dags/'

      - name: Upload DAGs files to S3
        if: steps.check_dags.outputs.files_exists == 'true'
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets[env.AWS_S3_BUCKET_NAME] }}
          AWS_ACCESS_KEY_ID: ${{ secrets[env.AWS_ACCESS_KEY_ID_NAME] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[env.AWS_SECRET_ACCESS_KEY_NAME] }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: './dags'
          DEST_DIR: 'dags/${{ env.REPO_NAME }}'

      - name: Check if Glue jobs folder exists
        id: check_glue_jobs
        uses: andstor/file-existence-action@v2
        with:
          files: './glue/jobs/'

      - name: Upload Glue jobs to S3
        if: steps.check_glue_jobs.outputs.files_exists == 'true'
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets[env.AWS_S3_BUCKET_NAME] }}
          AWS_ACCESS_KEY_ID: ${{ secrets[env.AWS_ACCESS_KEY_ID_NAME] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[env.AWS_SECRET_ACCESS_KEY_NAME] }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: './glue/jobs'
          DEST_DIR: 'dags/${{ env.REPO_NAME }}/glue'
